name: Build firmware

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options: 
          - Xiaomi-R3P
          - 360_T6M-PB
          - Arcadyan_WE410443-TC
          - Asus_RT-AC85P
          # 继续添加其他设备选项
        default: Xiaomi-R3P
      plugins:
        required: true
      customization:
        required: true
      firmwarever:
        required: true

env:
  REPOSITORY_URL: https://github.com/vb1980/padavan-4.4.git
  WORK_PATH: /opt/padavan-4.4
  FIRMWARE_PATH: /opt/firmwares
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_AUTHOR: vb1980

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Load default configurations from JSON
      id: load_defaults
      run: |
        default_plugins=$(jq -r '.plugins' defaults.json)
        default_customization=$(jq -r '.customization' defaults.json)
        default_firmwarever=$(jq -r '.firmwarever' defaults.json)

        # 如果未提供输入，则使用默认值
        echo "PLUGINS=${{ github.event.inputs.plugins || $default_plugins }}" >> $GITHUB_ENV
        echo "CUSTOMIZATION=${{ github.event.inputs.customization || $default_customization }}" >> $GITHUB_ENV
        echo "FIRMWARE_VER=${{ github.event.inputs.firmwarever || $default_firmwarever }}" >> $GITHUB_ENV

    - name: Setup environment
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential curl git
        sudo timedatectl set-timezone "$TIME_ZONE"

    - name: Clone source code and toolchain
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH && tar -Jxvf mipsel-linux-uclibc-gcc10-uClibcng1048.tar.xz -C toolchain-mipsel/toolchain-4.4.x

    - name: Load device settings
      run: |
        . ./device_settings.sh ${{ github.event.inputs.target }} $PLUGINS $CUSTOMIZATION

    - name: Configure firmware
      run: |
        . ./config.sh

    - name: Build firmware
      run: |
        cd $WORK_PATH && sudo make $MODEL
        mkdir -p $FIRMWARE_PATH && mv $WORK_PATH/trunk/images/*.trx $FIRMWARE_PATH

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: firmware-${{ env.model }}
        path: $FIRMWARE_PATH

    - name: Upload to anonfiles (optional)
      if: github.event.inputs.uploadanon == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer anon --no-progress $FIRMWARE_PATH/*.trx
