name: Build firmware

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options: 
          - Xiaomi-R3P
          - 360_T6M-PB
          - Arcadyan_WE410443-TC
          - Asus_RT-AC85P
          # 继续添加其他设备选项
        default: Xiaomi-R3P  # 确保与选项一致
      plugins:
        required: true
      customization:
        required: true
      firmwarever:
        required: true

env:
  REPOSITORY_URL: https://github.com/ifox6677/padavan-4.4.git
  WORK_PATH: /opt/padavan-4.4
  FIRMWARE_PATH: /opt/firmwares
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_AUTHOR: Padavan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
        check-latest: true
        cache-dependency-path: '**/go.sum'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin libev-dev \
          libssl-dev liblzo2-dev libpam0g-dev libevent-dev
        sudo timedatectl set-timezone "$TIME_ZONE"

    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH
        sed -i '/cp -f/d' Makefile  # 删除 Makefile 中的 cp -f 行

    - name: Extract toolchain
      run: |
        cp -f toolchain/mipsel-linux-uclibc-gcc10-uClibcng1048.tar.xz $WORK_PATH # 替换为工具链的实际路径
        cd $WORK_PATH
        mkdir -p toolchain-mipsel/toolchain-4.4.x  # 创建解压目标目录
        tar -Jxvf mipsel-linux-uclibc-gcc10-uClibcng1048.tar.xz -C toolchain-mipsel/toolchain-4.4.x  # 解压工具链

    - name: Load default configurations
      id: load_defaults
      run: |
        # 定义默认配置
        default_plugins='{"vpnsvr":"n","vpncli":"n","ss":"y","xray":"y","trojan":"y","ssobfs":"y","dnsforwarder":"n","adbyby":"n","adguardhome":"n","smartdns":"n","aliddns":"n","zerotier":"n","ddnsto":"n","wireguard":"n","frpc":"y","aldrive":"n","sqm":"y","mentohust":"n","scutclient":"n","njitclient":"n","minieap":"n","dogcom":"n"}'
        default_customization='{"lanip":"192.168.2.1","signaccount":"admin","signpassword":"admin","wifi2gssid":"","wifi5gssid":"","wifi2gpsk":"","wifi5gpsk":""}'
        default_firmwarever='20240403'

        # 使用输入值或默认值
        plugins=${{ github.event.inputs.plugins }}
        customization=${{ github.event.inputs.customization }}
        firmwarever=${{ github.event.inputs.firmwarever }}

        # 检查输入值，如果为空则使用默认值
        if [ -z "$plugins" ]; then
          plugins=$default_plugins
        fi
        if [ -z "$customization" ]; then
          customization=$default_customization
        fi
        if [ -z "$firmwarever" ]; then
          firmwarever=$default_firmwarever
        fi

        # 将最终值写入环境变量
        echo "PLUGINS=$plugins" >> $GITHUB_ENV
        echo "CUSTOMIZATION=$customization" >> $GITHUB_ENV
        echo "FIRMWARE_VER=$firmwarever" >> $GITHUB_ENV

    - name: Load device settings
      run: |
        . ./device_settings.sh "${{ github.event.inputs.target }}" "${{ env.PLUGINS }}" "${{ env.CUSTOMIZATION }}"

    - name: Configure firmware
      run: |
        . ./config.sh

    - name: Build firmware
      run: |
        cd $WORK_PATH && sudo make "$MODEL"  # 使用引号处理模型名称
        mkdir -p "$FIRMWARE_PATH" && mv "$WORK_PATH/trunk/images/*.trx" "$FIRMWARE_PATH"  # 使用引号处理路径

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: firmware-${{ env.model }}
        path: "$FIRMWARE_PATH"

    - name: Upload to anonfiles (optional)
      if: github.event.inputs.uploadanon == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer anon --no-progress "$FIRMWARE_PATH/*.trx"
